version: "3.8"

services:
  payment-gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./internal/config/config.yaml:/app/internal/config/config.yaml:ro
    restart: unless-stopped
