gateways:
  gatewayA:
    url: "http://{host}:{port}/mock-gateway-a"
    enabled: true
  gatewayB:
    url: "http://{host}:{port}/mock-gateway-b"
    enabled: true

middlewares:
  - context
  - auth
  - timeout
  - latencyTracker
  - logging
  - recovery

static:
  apiVersion: "v1"
  serviceName: "Payment-Gateway"
  defaultTimeoutSeconds: 10
  host: "0.0.0.0"
  port: 8000
