gateways:
  gatewayA:
    url: "http://{host}:{port}/mock-gateway-a"
    name: "GatewayA"
    enabled: true
  gatewayB:
    url: "http://{host}:{port}/mock-gateway-b"
    name: "GatewayB"
    enabled: true

middlewares:
  - context
  - auth
  - timeout
  - latencyTracker
  - logging
  - recovery

static:
  apiVersion: "v1"
  serviceName: "Payment-Gateway"
  defaultTimeoutSeconds: 10
  gatewayTimeoutSeconds: 5
  host: "0.0.0.0"
  port: 8000

cache:
  invalidationIntervalSeconds: 60
  ttlSeconds: 86400

resilience:
  httpTimeoutSeconds: 2
  maxRetries: 3
  initialBackoffMillis: 200
  maxBackoffMillis: 2000
  circuitBreaker:
    enabled: true
    maxRequests: 3
    intervalSeconds: 60
    timeoutSeconds: 30
    failureRatio: 0.6

workerPool:
  numWorkers: 11
  bufferSize: 200

